// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Suma.Infrastructure.Persistence;

#nullable disable

namespace Suma.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SumaDbContext))]
    [Microsoft.EntityFrameworkCore.Migrations.Migration("20260904073000_AddAccountNumberToAccounts")]
    partial class AddAccountNumberToAccounts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Suma.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_number");

                    b.Property<bool>("IncludeInAvailableToSpend")
                        .HasColumnType("INTEGER")
                        .HasColumnName("include_in_available_to_spend");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OpeningBalance", "Suma.Domain.Accounts.Account.OpeningBalance#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("AmountMinor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("opening_balance_minor");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency_code");
                        });

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Suma.Domain.Budgets.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("period_start");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ExpectedIncome", "Suma.Domain.Budgets.Budget.ExpectedIncome#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("AmountMinor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("expected_income_minor");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency_code");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PeriodEnd");

                    b.HasIndex("PeriodStart");

                    b.ToTable("budgets", null, t =>
                        {
                            t.HasCheckConstraint("ck_budgets_expected_income", "expected_income_minor >= 0");

                            t.HasCheckConstraint("ck_budgets_period", "period_start <= period_end");
                        });
                });

            modelBuilder.Entity("Suma.Domain.Budgets.BudgetAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("budget_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_id");

                    b.Property<bool>("ReserveFromAvailable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reserve_from_available");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Suma.Domain.Budgets.BudgetAllocation.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("AmountMinor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("amount_minor");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency_code");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BudgetId", "CategoryId")
                        .IsUnique();

                    b.ToTable("budget_allocations", null, t =>
                        {
                            t.HasCheckConstraint("ck_budget_allocations_amount_positive", "amount_minor > 0");
                        });
                });

            modelBuilder.Entity("Suma.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("IconKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_key");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_category_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("TransactionKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_kind");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Suma.Domain.Recurring.RecurringOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<Guid>("RecurringTransactionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("recurring_transaction_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId");

                    b.HasIndex("RecurringTransactionId", "DueDate")
                        .IsUnique();

                    b.ToTable("recurring_occurrences", (string)null);
                });

            modelBuilder.Entity("Suma.Domain.Recurring.RecurringTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_id");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_month");

                    b.Property<string>("DayOfWeek")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("day_of_week");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<Guid?>("DestinationAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("destination_account_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<string>("FrequencyUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("frequency_unit");

                    b.Property<int>("IntervalCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interval_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<int?>("MonthOfYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month_of_year");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<Guid?>("SourceAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_account_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Suma.Domain.Recurring.RecurringTransaction.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("AmountMinor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("amount_minor");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency_code");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("EndDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("SourceAccountId");

                    b.HasIndex("StartDate");

                    b.ToTable("recurring_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_recurring_transactions_amount_positive", "amount_minor > 0");

                            t.HasCheckConstraint("ck_recurring_transactions_dates", "end_date IS NULL OR start_date <= end_date");

                            t.HasCheckConstraint("ck_recurring_transactions_day_of_month", "day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_recurring_transactions_distinct_accounts", "source_account_id IS NULL OR destination_account_id IS NULL OR source_account_id <> destination_account_id");

                            t.HasCheckConstraint("ck_recurring_transactions_interval", "interval_count > 0");

                            t.HasCheckConstraint("ck_recurring_transactions_month_of_year", "month_of_year IS NULL OR month_of_year BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("Suma.Domain.Savings.GoalContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("SavingsGoalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("savings_goal_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Suma.Domain.Savings.GoalContribution.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("AmountMinor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("amount_minor");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency_code");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SavingsGoalId");

                    b.HasIndex("TransactionId");

                    b.ToTable("goal_contributions", null, t =>
                        {
                            t.HasCheckConstraint("ck_goal_contributions_amount_positive", "amount_minor > 0");
                        });
                });

            modelBuilder.Entity("Suma.Domain.Savings.SavingsGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("DestinationAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("destination_account_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_date");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TargetAmount", "Suma.Domain.Savings.SavingsGoal.TargetAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("AmountMinor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("target_amount_minor");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency_code");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("TargetDate");

                    b.ToTable("savings_goals", null, t =>
                        {
                            t.HasCheckConstraint("ck_savings_goals_target_positive", "target_amount_minor > 0");
                        });
                });

            modelBuilder.Entity("Suma.Domain.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<Guid?>("DestinationAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("destination_account_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OriginalTransactionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_transaction_id");

                    b.Property<Guid?>("SourceAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_account_id");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Suma.Domain.Transactions.Transaction.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("AmountMinor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("amount_minor");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency_code");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("OriginalTransactionId");

                    b.HasIndex("SourceAccountId");

                    b.HasIndex("TransactionDate");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_transactions_amount_positive", "amount_minor > 0");

                            t.HasCheckConstraint("ck_transactions_distinct_accounts", "source_account_id IS NULL OR destination_account_id IS NULL OR source_account_id <> destination_account_id");
                        });
                });

            modelBuilder.Entity("Suma.Domain.Budgets.BudgetAllocation", b =>
                {
                    b.HasOne("Suma.Domain.Budgets.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Suma.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Suma.Domain.Categories.Category", b =>
                {
                    b.HasOne("Suma.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Suma.Domain.Recurring.RecurringOccurrence", b =>
                {
                    b.HasOne("Suma.Domain.Recurring.RecurringTransaction", null)
                        .WithMany()
                        .HasForeignKey("RecurringTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Suma.Domain.Transactions.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Suma.Domain.Recurring.RecurringTransaction", b =>
                {
                    b.HasOne("Suma.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Suma.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Suma.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Suma.Domain.Savings.GoalContribution", b =>
                {
                    b.HasOne("Suma.Domain.Savings.SavingsGoal", null)
                        .WithMany()
                        .HasForeignKey("SavingsGoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Suma.Domain.Transactions.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Suma.Domain.Savings.SavingsGoal", b =>
                {
                    b.HasOne("Suma.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Suma.Domain.Transactions.Transaction", b =>
                {
                    b.HasOne("Suma.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Suma.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Suma.Domain.Transactions.Transaction", null)
                        .WithMany()
                        .HasForeignKey("OriginalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Suma.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
